name: newsapp310
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=17.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - altair==5.5.0
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - cachetools==6.1.0
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - click==8.2.1
      - feedparser==6.0.11
      - filelock==3.18.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - lxml==6.0.0
      - markupsafe==3.0.2
      - narwhals==1.46.0
      - newspaper4k==0.9.3.1
      - nltk==3.9.1
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-file==2.1.0
      - rpds-py==0.26.0
      - sgmllib3k==1.0.0
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - streamlit==1.46.1
      - tenacity==9.1.2
      - tldextract==5.3.0
      - toml==0.10.2
      - tornado==6.5.1
      - tqdm==4.67.1
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /opt/miniconda3/envs/newsapp310
